### PR TITLE
Dutch translation

### PR DESCRIPTION
**Pull request by DonutKakker**
All categories translated to dutch.

### CODE REVIEW

**Comment by danleveille** [comment]
@NLtranslator Please do fix them. :) I will merge these changes for now but please feel free to edit them. 👍

**Comment by NLtranslator** [comment]
Hi,

I’m new to Github.
How can I edit the translations?
If I know, then I will start changing them tomorrow.

Thanks,

Steven

**Comment by danleveille** [comment]
@NLtranslator No problem! It's easy to do. Just visit this file: https://github.com/dododex/translations/blob/master/categories.json

And click "edit" on the top right and you can edit the file in your browser. 😄

**Comment by NLtranslator** [comment]
I changed a lot of translations . A few covered the translations but did
not match the word as used in the app. I tried to find every word in the
app and translate it like that. However, I saw a lot of word still in
English in the app that were not in the translation file. Will these word
be added? Or can I add them myself to the file? Or are they not possible to
translate? Things like Monday, and “category tame able”.

Like to hear from you.

**Pull request merged**
