### PR TITLE
Update translations.js

### PR DESCRIPTION
**Pull request by Morgothu**
I know my translation can have a issues or something like this,but if you can check this,and send me answer what should i fix, I'll do it.

 
[Dododex Polish Translation.txt](https://github.com/dododex/translations/files/518331/Dododex.Polish.Translation.txt)

### CODE REVIEW

**Comment by danleveille** [comment]
Thank you so much, @Morgothu! So glad to see Polish translations! :)

There's a conflict with this pull request, so I'm going to merge your translations in with a separate pull request.

I noticed there was quite a few "≥" characters. For example, "zg≥aszane". Is that an error? Is it supposed to be "ł" (zgłaszane)?

**Comment by Morgothu** [comment]
So in Polish we have a some special letters like  ł,ś,ź,ż,ę,ó,ą,ć and I must try to change that to words without it? (It's very hard hah) and zg≥aszane=zgłaszane. So your suppose was good  ;)

**Comment by danleveille** [comment]
@Morgothu Thank you! I just wanted to check because it looks like the file replaced the ł letters with ≥. 

I published this to the live version of the translations, you can see here:
https://github.com/dododex/translations/blob/master/translations.js#L1341-L1603

It will be live in the next version of the app, so if you spot any errors once it's live, feel free to fix them here on Github. 👍 

Thank you so much!!

**Comment by Morgothu** [comment]
If i find any better options of translates I'll send it there  ;)

**Pull request closed without merging**
