### PR TITLE
Spanish translations

### PR DESCRIPTION
**Pull request by hector-romero**
Added missing translations.
Fixed some typos.
Improved some translations

### CODE REVIEW

**Comment by danleveille** [comment]
@hector-romero Thank you so much for your contributions! 

How would you like to be credited in the app? Name/website? :) I can always just use your Github if you prefer.

**Comment by hector-romero** [comment]
Whatever you think it's best. The nickname I like to use is hector22x, so that would be ok.

**Comment by danleveille** [comment]
Great! I will add that.

I plan on adding dino translations soon, but I don't have a file set up for that yet. In the meantime, if you'd like to contribute, you can add the translations to this ticket and I will include them in the translation file once its set up: #39

**Comment by hector-romero** [comment]
oh.. I didn't spend a single second looking at the issues, I didn't even think about that. I will keep an eye on it. Thanks!

**Pull request merged**
