### PR TITLE
Adding Vietnamese Langauge and Credit to translations.js

### PR DESCRIPTION
**Pull request by ShadoqTeam**

### CODE REVIEW

**Comment by danleveille** [comment]
@RaidenCage Hi -- I only see one phrase translated? Are you still working on it?

**Comment by RaidenCage** [comment]
Yes, We are still Working on it, Our Members are kind of unfamiliar with this kind of translation so I need to help them first

**Comment by RaidenCage** [comment]
> @RaidenCage Hi -- I only see one phrase translated? Are you still working on it?



> @RaidenCage Hi -- I only see one phrase translated? Are you still working on it?

Yes, We are still Working on it.

**Comment by RaidenCage** [comment]
@danleveille More Translations of Vietnamese has been done. And I'm who has emailed you with "phantuduy1209@gmail.com"

**Pull request closed without merging**
