### PR TITLE
Update RU translations.js

### PR DESCRIPTION
**Pull request by EgoSilentium**
Several missing translations.

### CODE REVIEW

**Comment by danleveille** [comment]
Hey @EgoSilentium (or maybe @NickGyver or @AncientD):

The term "more" is used a lot in the app, and sometimes in small places. Is there a shorter version of "Дополнительная информация". Does "больше" work?

**Comment by NickGyver** [comment]
Yep

**Comment by NickGyver** [comment]
but you can use term "show" - "показать", if it is under spoiler

**Comment by EgoSilentium** [comment]
Hey!

Can you send 1-2 examples of using "more" in small places?


ср, 17 окт. 2018 г., 8:11 Dan Leveille <notifications@github.com>:

**Comment by danleveille** [comment]
Oops, now that I'm looking into it, it's only used two times in the app, at the very bottom where it shows "Carryable By", etc. and in a new categories feature, "More" will be used to describe more categories. I will use "больше" in that case. 👍 

Thank you guys for the quick response!

**Comment by EgoSilentium** [comment]
Yes, in such cases you can use it without problems.

Any time!


ср, 17 окт. 2018 г., 8:50 Dan Leveille <notifications@github.com>:

**Pull request merged**
